---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: default
spec:
  channel: sre-testing
  secretRef:
    name: slack-webhook
  type: slack
  username: FluxBot

